### ISSUE TITLE
Telltale D3Dmesh exporter

### ISSUE THREAD

**Issue by xunilrj** [xunilrj/sandbox#18]
Hey @frostbone25, this may interest you. I created an exporter for d3dmesh for "Tales of Monkey Island". Still super incomplete., But it works. 

The major problem now is the "index buffer". Still don't know what to do with it.

code at: https://github.com/xunilrj/sandbox/tree/master/sources/rust/telltaled3dmesh
bin at: https://github.com/xunilrj/sandbox/releases/tag/telltaled3dmesh.0.0.1

**Comment by frostbone25** [comment]
I've been summoned. Bit late for me to reply but yeah this can help. I also think it'd be cool if you joined our server so we can discuss it more quickly and more in detail. [https://discord.gg/SPdn5yZr6M](https://discord.gg/SPdn5yZr6M)

We do now all the info that details the 6VSM .d3dmesh format and its data structures (among all other formats) so it might help you out quite a bit.
