### ISSUE TITLE
Is there an example with co_await working under webassembly?

### ISSUE THREAD

**Issue by unicomp21** [xunilrj/sandbox#2]

**Comment by xunilrj** [comment]
Purely, no. But there are tools that will allow you to use it.

https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html
https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#coroutines

**Comment by xunilrj** [comment]
https://github.com/WebAssembly/design/issues/1345
